function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry("baller8um", "Baller 8 (Unmarked)")
	AddTextEntry("ballerdefm", "Baller Defender (Marked)")
	AddTextEntry("sultcmrkunm", "Sultan Classic (Marked)")
	AddTextEntry("sandunm", "Sandstorm (Unmarked)")
	AddTextEntry("ukpurj", "Rebla (Marked)")
	AddTextEntry("ukpurhj", "Rhinehart Estate (Marked)")
	AddTextEntry("ukpucj", "Cypher (Marked)")
	AddTextEntry("ukpotsj", "Tailgator (Marked)")
	AddTextEntry("unjugular", "Jugular (Unmarked)")
	AddTextEntry("stdmark", "Oracle STD (Marked)")
	AddTextEntry("pdpantouk", "Panto (Marked)")
	AddTextEntry("gstsul1unm", "Sultan (Marked)")
	AddTextEntry("castigatorum", "Castigator (Unmarked)")
	AddTextEntry("buffalomark", "Buffalo (Marked) - Police")
	AddTextEntry("buffaloambo", "Buffalo (Marked) - EHS")
	AddTextEntry("unsunriser", "Sultan (Unmarked)")
	AddTextEntry("tempels", "Tempesta (Unmarked)")
	AddTextEntry("templbun", "Tempesta Custom (Unmarked)")
	AddTextEntry("attackunm", "Baller Attacker (Unmarked)")
	AddTextEntry("rsunm", "Sultan RS (Unmarked)")
	AddTextEntry("castmrkels_hems", "Castigator Marked")
	AddTextEntry("f340rpuk", "F340R Police")
	AddTextEntry("strmark", "Schneider STR PD")
	AddTextEntry("f140rpd", "F140r (Marked)")
	AddTextEntry("ballvmark", "Baller Venum (Marked)")
	AddTextEntry("komtmark", "Komoda Touring (Marked)")
	AddTextEntry("kurxmark", "Kuruma X (Marked)")
	AddTextEntry("vorschlag", "Vorschlag Retro (Marked)")
	AddTextEntry("swatvanr2", "Swatvan")
	AddTextEntry("rsxunm", "RSX")
	AddTextEntry("rhinehemsnonels", "Rhinehart (Marked)")
	AddTextEntry("ehsbike", "Bati RRV")
	AddTextEntry("buffalosxpolun", "Buffalo (Unmarked)")
	AddTextEntry("castmrk_intnon", "Castigator (Marked)")
	AddTextEntry("hycrs6", "Hycade RS6")
	AddTextEntry("ultrabee", "Ultra Bee")
	AddTextEntry("dguard", "DuneGuard")
	AddTextEntry("gstfmj1", "Vapid FMJ")
	AddTextEntry("gstjub1", "Jubilee CTX")
	AddTextEntry("accolade", "Accolade")
	AddTextEntry("aleutlift", "Aleutian (Lifted)")
	AddTextEntry("asea", "Asea Custom")
	AddTextEntry("ariant", "Ariant")
	AddTextEntry("asterope", "GZ Custom Mk2")
	AddTextEntry("baller", "Baller Custom")
	AddTextEntry("baller2", "Baller Custom Mk2")
	AddTextEntry("banshee", "Banshee ST")
	AddTextEntry("bf400", "400 Custom")
	AddTextEntry("bison", "Bison Custom")
	AddTextEntry("bjxl", "BeeJay XL Custom")
	AddTextEntry("blista", "Blista Custom")
	AddTextEntry("blista2", "Blista Custom Mk2")
	AddTextEntry("bolide", "2020 Bolide")
	AddTextEntry("boxville2", "EV-Grime")
	AddTextEntry("buffalo", "Buffalo Custom Mk2")
	AddTextEntry("buffalosl", "Buffalo SL")
	AddTextEntry("buffalowb", "Buffalo WB")
	AddTextEntry("caracara6x6", "Caracara 6x6")
	AddTextEntry("cavalcade", "Cavalcade Custom")
	AddTextEntry("cheetah", "Cheetah Custom")
	AddTextEntry("club", "Club Custom")
	AddTextEntry("comet2", "Comet Custom")
	AddTextEntry("comet6", "Comet Custom Mk2")
	AddTextEntry("comet6scw", "Comet 6")
	AddTextEntry("cometmansory", "Comet (Mansory Edition)")
	AddTextEntry("coquette", "Coquette Custom")
	AddTextEntry("cyphart", "Cyphart Estate")
	AddTextEntry("cypherhb", "Cypher H140i")
	AddTextEntry("deitymansory", "Deity (Mansory Edition)")
	AddTextEntry("dilettante", "Dilettante Custom")
	AddTextEntry("domgt", "Dominator GT")
	AddTextEntry("dubsta22", "Dubsta Custom")
	AddTextEntry("dubstag", "Dubsta-G")
	AddTextEntry("dukes", "Duke Custom")
	AddTextEntry("elegy2", "Elegy Custom Mk2")
	AddTextEntry("elegysa", "Elegy Classic Custom")
	AddTextEntry("ellie", "Ellie Custom")
	AddTextEntry("entityxf", "Entity XF Custom")
	AddTextEntry("feltzer2", "Feltzer Custom")
	AddTextEntry("flatbedm2", "Fleet Flatbed M2")
	AddTextEntry("fmlcctow", "Fleet Big Flatbed")
	AddTextEntry("fmlcctowdk", "DK Customs Flatbed")
	AddTextEntry("fmlcctowss", "SS Flatbed")
	AddTextEntry("fq2", "FQ-2 Custom")
	AddTextEntry("furoregt", "Furore GT Custom")
	AddTextEntry("futo", "Futo Custom")
	AddTextEntry("g63m", "Dubsta G63 (Mansory Edition)") 
	AddTextEntry("galaxyroamer", "Galaxy Roamer RV")
	AddTextEntry("gauntlet", "Gauntlet Custom")
	AddTextEntry("granger", "Granger Custom")
	AddTextEntry("gresly", "Gresley Custom")
	AddTextEntry("gstsul1", "Sultan Hycade")
	AddTextEntry("gstsulrs1", "Sultan Hycade Coupe")
	AddTextEntry("gstveto1", "Veto Go-Kart")
	AddTextEntry("H4RxST2", "Comet ST2")
	AddTextEntry("habanero", "Habanero Custom")
	AddTextEntry("hoonie", "Dinka Hoonie")
	AddTextEntry("huntley", "Huntley Custom")
	AddTextEntry("hycadetail", "Tailgator-S Hycade")
	AddTextEntry("hycenty", "Entity MT Hycade")
	AddTextEntry("hycsun", "Sunrise Hycade")
	AddTextEntry("sunrisehcwb", "Sunrise Hycade WB")
	AddTextEntry("infernus", "Infernus Custom")
	AddTextEntry("infernuswb", "Infernus")
	AddTextEntry("ingot", "Ingot Custom")
	AddTextEntry("issi3yd", "Issi (Yasid Design)")
	AddTextEntry("issi8s", "Issi-S 8")
	AddTextEntry("jakers_dominator9", "Dominator TRT ")
	AddTextEntry("jdom9", "Vapid Dominator V2")
	AddTextEntry("jgaunt4", "Gauntlet Custom")
	AddTextEntry("jubileemans", "Jubilee (Mansory Edition)")
	AddTextEntry("khamelion", "Khamelion Custom")
	AddTextEntry("kurumahyc", "Kuruma Hycade")
	AddTextEntry("kurwide", "Karuma Custom Widebody")
	AddTextEntry("landstalker", "Landstalker Custom")
	AddTextEntry("manchez", "Manchez Custom")
	AddTextEntry("manchez2", "Manchez Custom Mk2")
	AddTextEntry("mesa", "Mesa Custom")
	AddTextEntry("muler", "Fleet Flatbed Mule")
	AddTextEntry("monsterh", "Monster H")
	AddTextEntry("ninef", "Nine-F Custom")
	AddTextEntry("nspeedo", "Burgershot Van")
	AddTextEntry("nwkuruma", "Kuruma Widebody")
	AddTextEntry("omnisegt", "Omnis E-GT")
	AddTextEntry("oracle2", "Oracle Custom")
	AddTextEntry("packer", "Packer Custom")
	AddTextEntry("panto", "Panto Custom")
	AddTextEntry("pantor", "Panto-R")
	AddTextEntry("patriot", "Patriot Custom")
	AddTextEntry("penumbra", "Penumbra Custom")
	AddTextEntry("premier", "Premier Custom")
	AddTextEntry("r34hycade", "Elegy R34 Hycade")
	AddTextEntry("r300c", "R300-C")
	AddTextEntry("raiden", "Raiden Custom")
	AddTextEntry("rebla4x4", "Rebla 4x4")
	AddTextEntry("reblagtr", "Rebla GTR")
	AddTextEntry("reblahyc", "Rebla Hycade")
	AddTextEntry("rhinesed", "Rhinehart Sedan")
	AddTextEntry("radiantvff", "Radiant VFF")
	AddTextEntry("rocoto", "Rocoto Custom")
	AddTextEntry("sabregt", "Sabre GT")
	AddTextEntry("sanchez", "Sanchez Custom")
	AddTextEntry("sanchez2", "Sanchez Custom Mk2")
	AddTextEntry("schafter2", "Schafter Custom Mk2")
	AddTextEntry("schafter3", "Schafter Custom Mk3")
	AddTextEntry("schwark", "Schwartzer R4")
	AddTextEntry("sultan2c", "Sultan 2")
	AddTextEntry("schwarzer", "Schwarzer Custom")
	AddTextEntry("scv2", "Mustang")
	AddTextEntry("sg1150", "SG1150")
	AddTextEntry("sentinel", "Sentinel Custom")
	AddTextEntry("sentinel2", "Sentinel Custom Mk2")
	AddTextEntry("ssg_commet6", "Comet 6 SSG")
	AddTextEntry("stxbanshee", "Banshee ST-X")
	AddTextEntry("sunrise1", "Sunrise R")
	AddTextEntry("sunrisehc", "Hayes Sunrise")
	AddTextEntry("superd", "Jubilee Custom")
	AddTextEntry("surano", "Surano Custom")
	AddTextEntry("surge", "Surge EV Custom")
	AddTextEntry("tempestaes", "Tempesta-ES")
	AddTextEntry("tempestas", "Tempesta-S")
	AddTextEntry("tornado", "Tornado Custom")
	AddTextEntry("turismos", "Turismo S")
	AddTextEntry("vacca", "Vacca Custom")
	AddTextEntry("voltic", "Voltic Custom")
	AddTextEntry("warrener3", "Warrener Mk3")
	AddTextEntry("washington", "Washington Custom")
	AddTextEntry("windsor", "Windsor Custom")
	AddTextEntry("zr350 ", "ZR-350")
	AddTextEntry("gcscoot", "White Scooter")
	AddTextEntry("kurxa19", "Kuruma X")
	AddTextEntry("jogger", "Jogger (Vanilla Unicorn Van)")
	AddTextEntry("gbesperta", "Esperta Van")
	AddTextEntry("peptos_911rs", "Comet 911")
	AddTextEntry("zr", "ZR-350")
	AddTextEntry("vdcoffin02", "Halloween Coffin Mk2")
	AddTextEntry("lmnsrebla", "Rebla Mammoth")
	AddTextEntry("lmnsjester4", "Jester Mk4 Hycade")
	AddTextEntry("sunvoltx", "Sunrise Volt-X")
	AddTextEntry("clubc", "Carbon Club ")
	AddTextEntry("clubp", "Carbon Painted")
	AddTextEntry("obeyrs6jota", "RS6 Jota")
	AddTextEntry("argntvnm", "Argento Venum Hycade")
	AddTextEntry("dubmono", "Dubsta Mono")
	AddTextEntry("stxh", "Buffalo STX")
	AddTextEntry("iwagenelem", "I-Wagen Elemento")
	AddTextEntry("ven140", "Venum 140i Hycade")
	AddTextEntry("hweevil", "Weevil (Halloween Edition)")
	AddTextEntry("kuhlelegy", "Elegy Kuhl")
	AddTextEntry("sr8", "Kreiger SR8")
	AddTextEntry("sultlong", "Sultan Estate (Rally Edition)")
	AddTextEntry("everonb", "Everon-B")
	AddTextEntry("turismoc", "Turismo-C")
	AddTextEntry("ares", "Progen Ares")
	AddTextEntry("tempestafr", "Tempesta FR")
	AddTextEntry("elegy3", "Elegy Mk3")
	AddTextEntry("rs666", "RS6 Hycade")
	AddTextEntry("revabf", "Revolter Widebody")
	AddTextEntry("toreropt", "Torero-PT")
	AddTextEntry("neoncs", "Neon Custom Hycade")
	AddTextEntry("deluxowb", "Deluxo Widebody")
	AddTextEntry("deluxowb2", "Deluxo Widebody Mk2")
	AddTextEntry("yosemite6str", "Yosemite Mk6 STR")
	AddTextEntry("clubr", "Club-R")
	AddTextEntry("tailgatersr", "Tailgator SR")
	AddTextEntry("baller4x4", "Baller 4x4")
	AddTextEntry("blrmns", "Baller Mansory Edition")
	AddTextEntry("semnlift", "Canis Semi-lift")
	AddTextEntry("rsxven", "Itali RSX Ven")
	AddTextEntry("flatt", "Flatt")
	AddTextEntry("sentinel3wb", "Sentinel Classic LTO")
	AddTextEntry("cometsn", "Slantnose")
	AddTextEntry("sultx", "Sultan XS")
	AddTextEntry("sultxmas", "Sultan XS Xmas")
	AddTextEntry("hycsedan", "Rhinehart Sedan Hycade")
	AddTextEntry("rt3kvort", "Dinka RT3000 Vortex")
	AddTextEntry("bati1000r", "Bati 1000r")
	AddTextEntry("mvolt", "M-VOLT")
	AddTextEntry("f340r", "F340-R")
	AddTextEntry("gresleyhellfire", "Gresley Hellfire")
	AddTextEntry("caracara24x4", "Caracara Lifted")
	AddTextEntry("caracara2mst", "Caracara Monster")
	AddTextEntry("tenfgt2", "Ten-F LMS GT2")
	AddTextEntry("dawn", "Dawn")
	AddTextEntry("jubven", "Jubilee Venuum")
	AddTextEntry("rebelc2", "Rebel Coyote")
	AddTextEntry("doubleh2", "Double-T H2")
	AddTextEntry("briosoav", "Brioso X")
	AddTextEntry("sandkingrv", "Sandking RV")
	AddTextEntry("brickaderv", "Brickade RV")
	AddTextEntry("zentven", "Zentorno Venuum")
	AddTextEntry("rhineadro", "Rhinehart Adro")
	AddTextEntry("cast4x4", "Castigator 4x4")
	AddTextEntry("cyphermax", "Cypher (Maxton Design)")
	AddTextEntry("elegyrow", "Elegy Rowen")
	AddTextEntry("jubileedelta", "Jubilee Urban 4x4")
	AddTextEntry("tenfevo", "10F Mansory Evo")
	AddTextEntry("torosv", "Toros Vorsteiner")
	AddTextEntry("turismolbwk", "Turismo Classic LBWK")
	AddTextEntry("xlskey", "XLS Keyvany")
	AddTextEntry("comtech", "Comet Techart")
	AddTextEntry("electricscooter", "Scooter (Custom)")
	AddTextEntry("clubrhyc", "Club-R Hycade")
	AddTextEntry("shogunhr", "Nagasaki Shogun HR")
	AddTextEntry("hycm5", "Hycade M5")
    AddTextEntry("nerops", "Truffade Nero Pur Sport")
	AddTextEntry("rrinfernusx", "Infernus Extreme")
	AddTextEntry("cometmath", "Comet Manthey")
	AddTextEntry("pacesultrs", "Sultan RS Custom")
	AddTextEntry("pomule", "Post Op Mule")
	AddTextEntry("tenfmax", "10f Max")
	AddTextEntry("polycypbla", "Cypher B")
	AddTextEntry("sentinel6", "Sentinel STD Touring")
	AddTextEntry("shinobid", "Shinobi Drag")
	AddTextEntry("cyphermans", "Cypher Mans")
	AddTextEntry("carabb", "Caracara Slammed")
	AddTextEntry("gstsentgs2", "Sentinel GTS RAMPAGE")	
	AddTextEntry("cholo", "Cholo Lord")
	AddTextEntry("gstsulc1", "Sultan Classic CTX")
	AddTextEntry("pacearg", "Argento P Custom")
	AddTextEntry("hellspawn", "Hellspawn")
	AddTextEntry("moscooter1", "Scooter")
	AddTextEntry("polec135", "NPAS")
	AddTextEntry("hemsec135", "HEMS")
	AddTextEntry('komodagta', 'Lampadati Komoda GTA')
	AddTextEntry('issisp', 'Issi Sport Plus')
	AddTextEntry('borneo', 'Borneo')	
	AddTextEntry('borneo2', 'borneo XL')	
	AddTextEntry('borneo3', 'Borneo Offroad')
	AddTextEntry('peacemaker', 'Peacemaker 1')	
	AddTextEntry('peacemaker2', 'Peacemaker 2')
	AddTextEntry('peacemaker3', 'Peacemaker 3')	
	AddTextEntry('peacemaker4', 'Peacemaker 4')	
	AddTextEntry('peacemaker5', 'Peacemaker 5')	
	AddTextEntry('peacemaker6', 'Peacemaker 6')
	AddTextEntry('jogger', 'Jogger')	
	AddTextEntry('joggerpas', 'Jogger Minibus')	
	AddTextEntry('imperial', 'Imperial')
	AddTextEntry('imperialpas', 'Imperial Minibus')	
	AddTextEntry('imperialev', 'Imperial EV')	
	AddTextEntry('bypdbe', 'Youga PDB Edition')		
end)
